version: '3.8'

services:
  # Auth Service
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    networks:
      - auth-network

  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: auth-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - auth-network

  # Redis
  redis:
    image: redis:latest
    container_name: auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - auth-network

volumes:
  mongodb_data:
  redis_data:

networks:
  auth-network:
    driver: bridge